### ISSUE TITLE
Move Observatorium metrics/log storage to Ceph 

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1465]
Rn buckets are hosted on MOC NFS server which is not being maintained anymore.

- [x] Create 2 Object Bucket Claims in the `opf-observatorium` namespace (https://github.com/operate-first/apps/pull/1631)
- [ ] Migrate metrics and log data from current buckets to the new buckets
- [ ] Update Observatorium credentials to use the new buckets

**Comment by larsks** [comment]
@bryanmontalvan note that instead of handling this migration externally, as we've discussed in chat, you could alternatively submit a pod to the cluster that would perform the migration internally. The pod would have access to all the necessary secrets (either exposed as environment variables or mounted as files on the filesystem).

I think that's probably the right way to handle this.

**Comment by HumairAK** [comment]
stale, closing.
