### ISSUE TITLE
How to check/Debug `kustomization` deployments locally

### ISSUE THREAD

**Issue by eranra** [operate-first/apps#154]
I am trying to debug https://github.com/operate-first/apps/pull/153/ on my local OCP cluster.

I executed the bellow command and got errors. I see that  `components` is indeed not expectd by kustomization but I see that in all other files ... need help in debug

```
$ oc apply -k cluster-scope/base/namespaces/openshift-logging
error: json: unknown field "components"
```

@durandom @4n4nd @tumido @drbwa

**Comment by durandom** [comment]
often it's a mismatch in the tooling, e.g. wrong `oc` or `kustomize` version. In case you're on a Linux box, you can check out https://github.com/operate-first/toolbox which has all the required tools installed.

**Comment by tumido** [comment]
Hi @eranra,

you need to compose the manifests via kustomize first in order to apply them. See https://kustomize.io/ As @durandom said, you can use our toolbox or you can also install the tooling by yourself. Then you can apply the manifests like this:

```
kustomize build cluster-scope/base/namespaces/openshift-logging | oc apply -f -
```

Kustomize is also packaged within  `kubectl` and `oc` clients  (see this [docs](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#how-to-apply-view-delete-objects-using-kustomize)). But the Kustomize in it is pretty basic and dated. The error you see about `components` suggests this problem. You see, components are pretty recent addition to Kustomize, so it's probably not yet available in the Kustomize your `oc` client is packaged with.

**Comment by durandom** [comment]
@eranra did this resolve the issue? 
@tumido @HumairAK is this something we could've documented somewhere?
In the https://github.com/operate-first/apps README? 
Might be a valid use case to deploy/test the PR via the cli...

**Comment by eranra** [comment]
@durandom I worked today on trying to get more accurate set of files into the PR learning from CLO documentation and getting a lot of help from @tumido with regards to specific list of components we wll deploy. 

I did not "yet" tryied to deploy this on my local OCP cluster ... hope to have cycles soon to do that.

 I totally agree that documenting "how to test your changes to deployment etc. :" might be good area to create documenation. Also, @tumido if there chould be CI test that tries to deploy and provides feedback on the result it will also be very useful.

**Comment by eranra** [comment]
@durandom ref to relevant PR:: https://github.com/operate-first/apps/pull/153

**Comment by tumido** [comment]
We can do a guide for Kustomize. :slightly_smiling_face: I think that would be helpful. :+1: https://github.com/operate-first/support/issues/58

**Comment by eranra** [comment]
@tumido thanks ... with `kustomize build` I was able to get the needed .yaml files. Not sure why this did not work with `kubectl -k` maybe as you highlighted something that has to do with versions.
