### ISSUE TITLE
Order of resources under overlays/moc/kustomization.yaml

### ISSUE THREAD

**Issue by eranra** [operate-first/apps#164]
Hi @tcoufal with regards to the file https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/kustomization.yaml ... I really think that lexicographic order of the `resource` files under might not be the correct way to go ... consider somehow to group them in logical order (maybe per subject, area) or maybe have another hierarchical file per subject ... not critical but will probably help.

Also, I was looking to add some references to where the information on deployment was taken from ... maybe as part of that file, and maybe outside somewhere

**Comment by tumido** [comment]
> consider somehow to group them in logical order (maybe per subject, area)

Yeah, maybe we would need to group them by some key. The main point of the `cluster-scope` application though is not to "deploy set of projects" or "deploy all resources in a cluster", it should rather be a bootstrap repository we can use to set up the cluster resources. So we don't want to have any project specific resources like `Deployment`s, `Service`s or `Route`s in there at all... Those resources should be kept in the application/project specific folder/repository and pulled in to the cluster by ArgoCD as a separate application.

The `cluster-scope` application (the term "application" may be misleading here but I don't have a better word for it) is ops-centric, not dev-centric. It should be friendly to the ops users who take care of what gets deployed to a particular cluster - on the cluster administrator level. Considering this aspect is the main focus of the application - I think we should be grouping the resources by a resource kind rather than the subject.

In the end, I agree, that some grouping may be necessary (like to introduce some nesting) because we don't want that resource list in `overlay/X/kustomization.yaml` to grow indefinitely.

Grouping by subject is achieved at the application/project level, since each application is meant to be about a single project. On the other hand, the `cluster-scope` app purpose is to (mostly) define resources which have to be unique for the whole cluster 0 therefore grouping them or ordering them per subject doesn't make much sense to me - you need to be certain that the resource is pulled into the overlay only once, etc. 

> Also, I was looking to add some references to where the information on deployment was taken from ... maybe as part of that file, and maybe outside somewhere

Can you elaborate on that? Do you mean like additional comments and descriptions to a resource and such? If so, I think I'd rather see that part of the individual resources - like annotations or labels, since this appears to be to be orthogonal to the resource kinds and even namespaces and projects. Would something like that be acceptable solution?

@HumairAK do you have any thoughts on that?

(btw. `@tcoufal` is not my GH handle. :smile: - I had to double check this is not my account by some accident. It seems it isn't...)

**Comment by eranra** [comment]
@tumido I was exactly thinking on "comments and descriptions to a resource and such" ... you are correct that we can add those in the resource scope but what I faced with the CLO deployment is multiple resources from various types ... so, I guess I can add to all resources the same link ... NP

**Comment by HumairAK** [comment]
I'm not _entirely_ sure if I understand the problem. If it's just a matter of having a long list in alphabetical order under `resources` being hard to discern. We could move them in separate directories so it looks something like: 

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- groups/
- namespaces/
- crds/
- etc.
```
Then store these resources within the environment's own directory i.e:
- `cluster-scope/overlays/moc/groups/`
- `cluster-scope/overlays/moc/namespaces/`
- `cluster-scope/overlays/moc/crds/`
- etc. 

Where each directory contains the resources accompanied by their own `kustomization.yaml`

**Comment by tumido** [comment]
@HumairAK yes, that's what I think as well:

>  I think we should be grouping the resources by a resource kind rather than the subject.

I don't think it's that much of a deal rn. And I actually think the initial issue was raised due to a bit of misunderstanding of the `cluster-scope` app purpose. Because - in case you start stashing application manifests in there, you want to group them by "subject" - the app it belongs to. But the essential reason for `cluster-scope` app existence is not meant for apps. As Christoph is suggesting, we should at least describe this "`cluster-scope` purpose" in the README or somewhere.

**Comment by HumairAK** [comment]
We could simply add a readme within the cluster-scope folder, thoughts?

**Comment by tumido** [comment]
yeah, that's what I thought...
