### ISSUE TITLE
[workload-overview] Identify what information should be displayed in the overview dashboard

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1652]
We need to display information about a service/application that is deployed on operate first clusters.

The current suggestion is:
- Project owner github handle
- Resources being consumed by the project (cpu, memory, storage,...)
- Link to some basic documentation about the project
- Link to the PR where the project namespace was created

**Comment by HumairAK** [comment]
I think that's a good list. IMO I also think we should also keep in mind that: 

- information should be publicly displayable (no cluster internal data/secrets/etc.) 
- information should be high level, and not super technical (if we show resource usage, it should be very minimal, so that a non-technical/ops person can also digest it, we already have detailed resource dashboards for operations)

**Comment by 4n4nd** [comment]
initial iteration of the workload overview dashboard added in: https://github.com/operate-first/apps/pull/1832
