### ISSUE TITLE
[workload-overview] How can we make the dashboard public?

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1662]
If we make a single stop grafana dashboard for opf workloads, how do we make it public since the current grafana instance is behind a proxy.

**Comment by bryanmontalvan** [comment]
After some digging, I think that going the snapshot route would be a good since if we share a snapshot of a dashboard or panel the following happens to both dashboard and panel snapshots.
> Grafana strips sensitive data like queries (metric, template and annotation) and panel links, leaving only the visible metric data and series names embedded into your dashboard. Dashboard snapshots can be accessed by anyone with the link.

The only difference between **dashboard snapshots** and **panel snapshots** is that panel snapshots can be embedded to a web-page using `<iframe src="https://play.grafana....">` 

The only issue I'm seeing is that **"Are these snapshot dashboards being updated live?"** Because after some testing it seems to only show the metrics from the time that the **snapshot share link** was created to 6 hours before that. And whenever another time-frame is selected an `Unauthorized` error is shown.

**Links:**
Share a panel: https://grafana.com/docs/grafana/latest/sharing/share-panel/
Snapshot API: https://grafana.com/docs/grafana/latest/http_api/snapshot/

**Comment by 4n4nd** [comment]
@bryanmontalvan Yeah we want the data to not be static. So if a new service/app is onboarded, the dashboard should update automatically to include it.

I think @HumairAK's suggestion to go with a separate public grafana instance makes more sense for this.

**Comment by HumairAK** [comment]
we have a public grafana instance now for public dashboards https://github.com/operate-first/apps/tree/master/grafana/overlays/moc/smaug-public
