### ISSUE TITLE
Potential security issue with namespace owners being able to deploy their own kfdefs

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#167]
so because namespace admins are allowed to deploy their own kfdefs, they essentially can do whatever the odh-operator can and as far as I know the odh-operator has much higher privileges than a namespace admin. We need default rbacs for the namespace admin that don't allow them to create/edit kfdefs to prevent privilege escalation.

**Comment by tumido** [comment]
yes, this is a problem we need to solve at some point. I wanted to tackle this as part of the ADR
https://github.com/operate-first/blueprint/issues/23 

However I don't have any good recipe, how to actually solve it. The Kubernetes rbac is purely additive, there are no restrict rules. And since the ODH operator itself is granting all users to deploy a Kfdef there's not much to do without actually requesting the ODH operator to change its behavior (either changing this upstream or forking). 

A possible workaround is to restrict this in ArgoCD on projects level (putting the kfdef resource on a resource blacklist), but that solves it only for the ArgoCD deployed apps. Openshift project admin can still do it manually.

**Comment by HumairAK** [comment]
From what I can tell, these aggregate roles in particular will need to be changed: 
`kfdefs.kfdef.apps.kubeflow.org-v1-admin`
`kfdefs.kfdef.apps.kubeflow.org-v1-edit`

We should request from upstream to allow us to hand out these roles by ourselves.

**Comment by tumido** [comment]
@HumairAK you awake? :smile: wanna you join me on a mtg?

**Comment by HumairAK** [comment]
Resolved in #206
