### ISSUE TITLE
Create an exploration type of notebook to see what data we have available w.r.t onboarding applications, and what are some possible metric definitions.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1957]
Furthers: https://github.com/operate-first/support/issues/571

**Comment by HumairAK** [comment]
@chauhankaranraj can you flesh this issue out

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj can you flesh this issue out

Just realized I can't edit the issue description, so adding it here :)

As a product owner,
I want to understand what kind of data can be collected from opf github repos wrt onboarding, and explore it,
So that I can determine what are some possible metrics/dimensions I can define to evaluate the onboarding process

**Acceptance Criteria**
- [ ] notebook to collect onboarding related issues and prs from the support and apps repos
- [ ] define some possible metrics related to "time to onboard", as well as visualize and compare them
