### ISSUE TITLE
Add cert manager for osc-cl2 and osc-cl1

### ISSUE THREAD

**Issue by caldeirav** [operate-first/apps#1974]
Edit by @HumairAK : 

Related: https://github.com/operate-first/support/issues/1006

**Comment by durandom** [comment]
@redmikhail https://github.com/operate-first/apps/search?q=jerry+cert+manager just got cert-manager installed. You can use those PRs to get the same setup for os-climate

/assign @redmikhail

**Comment by HumairAK** [comment]
also see: https://github.com/operate-first/apps/issues/1998#issuecomment-1130635032 

we may not be able to use cert-manager operator for this and may require a manual cert-manager installation

**Comment by redmikhail** [comment]
@HumairAK going through the issues in cert-manager repo I came across of this one https://github.com/cert-manager/cert-manager/issues/506 . Wonder if it will resolve the issue we are facing (eg. using https validation instead of the resolver) . I will update https://github.com/os-climate/os_c_data_commons/issues/114 issue with findings
