### ISSUE TITLE
Add documentation on how to use vault on operate first

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1992]
Docs should focus on the cluster admin persona for now. Project admin persona is less critical right now and not high priority.

Explain how admins can get access to vault and ESO to store their secrets securely in the vault instance. What manifests need to be created? 

Who needs to be contacted for changes/additions vault side? 

Related: https://github.com/operate-first/support/issues/298

**Comment by SamoKopecky** [comment]
/remove-lifecycle stale

@HumairAK It seems to me the documentation for Vault is complete, can we close this?

**Comment by Gregory-Pereira** [comment]
I have a follow on question to this. I see that in vault when creating a secret it doesn't let you specify the top level property, it defaults to `Data`. For those not understanding what I am referring to, some other values for what I am calling a "top level property" (for lack of a better term) within a k8s secret would be things like: `apiVersion`, `kind`, `type`, `metadata`, `stringData`, etc. My question is about the interaction between vault when it comes to the difference with `Data` and `stringData`, Which should we use when creating secrets? Also how would we go about creating one with `stringData`, simply string enclose the values (which I think from a k8s perspective would make the values equivalent)? I am also aware that `stringData` for secrets does not get encrypted where as Data does, so does that mean we would never create something with a `stringData` property in vault, because its not really a secret then, more of a glorified configmap?
