### ISSUE TITLE
[kubeflow] Unable to override default upstream configuration

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#213]
The kubeflow dashboard deployment is configured using a params file ([here](https://github.com/kubeflow/manifests/blob/master/stacks/openshift/config/params.env)) which is used in the centraldashboard deployment. I have tried overriding the params file (to customize our kubeflow deployment) as well as the centraldashboard deployment but have not been successful in doing so.

Maybe I am doing something wrong here, but can anyone look into this issue?

The only solutions I could think of is either 
- making changes to the upstream default configuration (not super feasible, but we can at least disable automatic registration/namespace creation for new users)
- forking the centraldashboards repo and making the changes in our fork

**Comment by HumairAK** [comment]
So background: we want to turn off automatic auth as described [here](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#automatic-creation-of-profiles) via the dashboard. 

In the kubeflow deployment this gets translated to an env var that gets added to the deployment spec. In our kfdef this is generated [here](https://github.com/operate-first/apps/blob/master/kubeflow-components/base/kfdef.yaml#L47). We could try to patch this, via an overlay, and if it works great. The source of the deployment is [here](https://github.com/kubeflow/manifests/tree/master/common/centraldashboard/overlays/stacks). 

If we can't patch this, I'm thinking of just getting the final generated result of `kubeflow-apps` and just putting that in our repo and patching it manually, it'd be like 5-10 yamls I think, I don't think that would be that big of a deal to maintain.

**Comment by 4n4nd** [comment]
> If we can't patch this, I'm thinking of just getting the final generated result of `kubeflow-apps` and just putting that in our repo and patching it manually, it'd be like 5-10 yamls I think, I don't think that would be that big of a deal to maintain.

Yes that is what I meant by forking the centraldashboards repo

**Comment by tumido** [comment]
So, things are a bit different that they appear:

1. This `kfdef` is using stacks and v3 of kubeflow manifests.
2. This `kubeflow-apps` is a magical application in kfdef, which is magical by definition and makes the whole kfdef highly opinionated - a mere presence of `kubeflow-apps` application, disables `parameters` or `overlays` for all applications for example.
 
https://www.kubeflow.org/docs/other-guides/kustomize/
![image](https://user-images.githubusercontent.com/7453394/107219158-f9ecd180-6a10-11eb-9ae6-aaff9ce75570.png)

3. Since v3 all of the configuration happens via configmaps, not via parameters/overlays anymore. (ODH is using v2, so that's not affected yet). The documentation for this is not yet in place on the website. See this issue for more details on how it should work: https://github.com/kubeflow/manifests/issues/1062
3. Our kfdef uses `stacks/openshift` this stack is not even patching the centraldashboard deployment with that environment variable (it's not using the [`centraldash/base/deployment_patch.yaml`](https://github.com/kubeflow/manifests/blob/master/common/centraldashboard/base/deployment_patch.yaml) at all. It uses [`centraldash/base_v3/deployment_patch.yaml`](https://github.com/kubeflow/manifests/blob/master/common/centraldashboard/base_v3/deployment_patch.yaml) and [`centraldash/overlays/stacks/deployment_kf_config.yaml`](https://github.com/kubeflow/manifests/blob/master/common/centraldashboard/overlays/stacks/deployment_kf_config.yaml) instead). That means getting the value into the [`params.env`](https://github.com/kubeflow/manifests/blob/master/stacks/openshift/config/params.env) won't help at all, because there's no way it gets propagated to the deployment. This has to be solved by an upstream PR.
4. The [`params.env`](https://github.com/kubeflow/manifests/blob/master/stacks/openshift/config/params.env) is rendered into `kubeflow-config` global config. There's currently no way how to patch a stack's settings, since overlays/parameters/multiple definitions are not supported in v3.

Because of all the above we have to:
1. Patch the `deployment_patch` upstream
2. Create a new kubeflow stack for ourselves, since that's the only way how to change settings in there.

Let's try this out:
https://github.com/kubeflow/manifests/pull/1736

For the time being, we can point the kfdef to my branch for the manifests, which should propagate the change properly:
https://github.com/operate-first/apps/pull/219

**Comment by HumairAK** [comment]
Great work @tumido, the fork seems to introduce minimal changes so I dont' expect it to be too much work to maintain while we wait for the PR upstream.

**Comment by 4n4nd** [comment]
Yes! ++ Awesome work :100:
