### ISSUE TITLE
Fybrik CRDs preventing Smaug Cluster-Resources app from syncing successfully

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2278]
ArgoCD App: https://argocd.operate-first.cloud/applications/cluster-resources-smaug?resource=sync%3AOutOfSync&operation=true

Example sync error for resources: 
CustomResourceDefinition.apiextensions.k8s.io "plotters.app.fybrik.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions

It is complaining about: https://github.com/operate-first/apps/blob/master/cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml#L499

The PR in question: https://github.com/operate-first/apps/pull/2220

The kubeval test seemed to indicate passing before I merged it. But seemed to leave another comment after merge indicating it failed, logs are expired so I'm not sure if it as complaining about this particular issue.

**Comment by durandom** [comment]
@roytman I think this probably a validation of the fybrik CRDs. Do you have an idea what's going on here?

**Comment by durandom** [comment]
@mimotej I ran your script

```
[root@8f7be13d6c8d apps]# test-kubeval-validation
Checking all overlays.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1063  100  1063    0     0   5110      0 --:--:-- --:--:-- --:--:--  5262
checking ./argocd-notifications/overlays/infra
PASS - stdin contains a valid ServiceAccount (argocd.argocd-notifications-controller)
PASS - stdin contains a valid Role (argocd.argocd-notifications-controller)
PASS - stdin contains a valid RoleBinding (argocd.argocd-notifications-controller)
PASS - stdin contains a valid ConfigMap (argocd.argocd-notifications-cm)
PASS - stdin contains a valid Secret (argocd.argocd-notifications-secret)
PASS - stdin contains a valid Service (argocd.argocd-notifications-controller-metrics)
PASS - stdin contains a valid Deployment (argocd.argocd-notifications-controller)
checking ./prow/overlays/smaug
ERR  - stdin: Failed initializing schema https://raw.githubusercontent.com/operate-first/schema-store/main/schemas/master-standalone-strict/role-rbac-v1beta1.json: Object has no key 'io.k8s.api.rbac.v1beta1.PolicyRule'
ERR  - stdin: Failed initializing schema https://raw.githubusercontent.com/operate-first/schema-store/main/schemas/master-standalone-strict/rolebinding-rbac-v1beta1.json: Object has no key 'io.k8s.api.rbac.v1beta1.RoleRef'
Aborting due to errexit on line 45. Exit code: 1
```

Can you explain these errors?

**Comment by roytman** [comment]
> @roytman I think this probably a validation of the fybrik CRDs. Do you have an idea what's going on here?

Checking

**Comment by roytman** [comment]
The error is not clear to me 

> CustomResourceDefinition.apiextensions.k8s.io "plotters.app.fybrik.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions

> It is complaining about: https://github.com/operate-first/apps/blob/master/cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml#L499

I was under the impression that K8s sets the values into the `CustomResourceDefinitionStatus.storedVersions` 
Furthermore, the K8s [spec](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/#CustomResourceDefinitionStatus) explicitly mentions that "The field is mutable"

**Comment by mimotej** [comment]
@durandom 
> @mimotej I ran your script
> 
> ```
> [root@8f7be13d6c8d apps]# test-kubeval-validation
> Checking all overlays.
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1063  100  1063    0     0   5110      0 --:--:-- --:--:-- --:--:--  5262
> checking ./argocd-notifications/overlays/infra
> PASS - stdin contains a valid ServiceAccount (argocd.argocd-notifications-controller)
> PASS - stdin contains a valid Role (argocd.argocd-notifications-controller)
> PASS - stdin contains a valid RoleBinding (argocd.argocd-notifications-controller)
> PASS - stdin contains a valid ConfigMap (argocd.argocd-notifications-cm)
> PASS - stdin contains a valid Secret (argocd.argocd-notifications-secret)
> PASS - stdin contains a valid Service (argocd.argocd-notifications-controller-metrics)
> PASS - stdin contains a valid Deployment (argocd.argocd-notifications-controller)
> checking ./prow/overlays/smaug
> ERR  - stdin: Failed initializing schema https://raw.githubusercontent.com/operate-first/schema-store/main/schemas/master-standalone-strict/role-rbac-v1beta1.json: Object has no key 'io.k8s.api.rbac.v1beta1.PolicyRule'
> ERR  - stdin: Failed initializing schema https://raw.githubusercontent.com/operate-first/schema-store/main/schemas/master-standalone-strict/rolebinding-rbac-v1beta1.json: Object has no key 'io.k8s.api.rbac.v1beta1.RoleRef'
> Aborting due to errexit on line 45. Exit code: 1
> ```
> 
> Can you explain these errors?

Ran that locally and everything passed. I don't see here following warning?
```
WARN - Set to ignore missing schemas
```
If not you are propably using old version of the script. Old version is not using `--ignore-missing-schemas` flag which outputs warning mentioned above and ignores CRDs that don't have valid schema in the schema store. That is why there are these error because it can't find CRDs for these resource - they do not exist for some reason...

To why kubeval passed on this situation. From what I was able to find the CRD should be valid (at least from the kubeval's point of view) as mentioned @roytman `CustomResourceDefinitionStatus.storedVersions` should be mutable and should support array or null where items of the array are either null or string - schema which validates it is [here](https://raw.githubusercontent.com/operate-first/schema-store/main/schemas/master-standalone-strict/customresourcedefinitionstatus-apiextensions-v1.json) 
Not sure why ArgoCD complains about it then :thinking: also :

>Example sync error for resources:
CustomResourceDefinition.apiextensions.k8s.io "plotters.app.fybrik.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions

seems to indicate to me that it doesn't like that value `v1alpha1` is present in the `status.storedVersions[0]` 
but in the [actual manifest](https://github.com/operate-first/apps/blob/master/cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml#L499). There is empty array so my guess it that something appends to it and ArgoCD dislikes that for some reason? Not sure... tho

**Comment by roytman** [comment]
I think, the error is happened because in the past we supported the `v1alpha1` version, and now we moved to `v1beta1`. We do not support `v1alpha1` anymore, and it is not in the `spec.versions`, but K8s contains the old `v1alpha1` instances. 

Is it possible to uninstall fybrik CRDs and install again with the new version only.

**Comment by HumairAK** [comment]
deleting and resyncing fixed the issue, thanks @roytman

**Comment by durandom** [comment]
> deleting and resyncing fixed the issue, thanks @roytman

Is this some checkbox in argocd? Is this something we should add to a argocd runbook?

**Comment by HumairAK** [comment]
@durandom no, I manually deleted the resources and re created them with argocd -- as far as I understand it, this is not an issue on our end. This seems like a very niche case, but in the future we can try doing `replace` update in argocd, this a checkbox that appears when you click `sync` : 

![image](https://user-images.githubusercontent.com/10904967/186685097-c46d9324-4157-4381-a92d-319d7629d65b.png)
