### ISSUE TITLE
Operate-first prow / CI issues from `kubeval` check

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/apps#2288]
Prow has been slow recently, and a few PRs are being blocked due to their kubeval check failing [see example](https://github.com/operate-first/apps/pull/2284). My theory is these performance issues are related to that kubeval check itself, in that it is not currently checking the diff, but the entire repo as you can see in [that check example log](https://s3-rook-openshift-storage.apps.morty.emea.operate-first.cloud/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/2284/kubeval-validation/1562465512301006848/build-log.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=VTDRNIJYZWVQXZ7PGQTP%2F20220824%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220824T171834Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=6a945c82a4ef610a8d8fb26b51dda536969256676f2d52922655ed51975ae314). It eventually values with an exit code `137` which means it is dying due to memory constraints. Can kubeval be set to run only against the diff produced by the PR @mimotej? If not we can consider upping the [resources per PR](https://github.com/operate-first/apps/blob/master/.prow.yaml#L33-L38) (although that could become pretty intensive), or we should consider removing the check entirely.

/cc @mimotej

**Comment by Gregory-Pereira** [comment]
There was a similar issue with precommit a while back. Not sure if this solution is repeatable here but sharing it for reference: 
https://github.com/thoth-station/prescriptions/pull/27401/files.
https://github.com/thoth-station/prescriptions-refresh-job/issues/52#issuecomment-1217942813

**Comment by Gregory-Pereira** [comment]
So it turns out it is checking for a diff as seen (here)[https://github.com/operate-first/toolbox/blob/master/scripts/test-kubeval-validation#L8-L12]. However running that against (my example pr)[https://github.com/operate-first/apps/pull/2284] produces this:
```
$PULL_BASE_SHA="281d08f5c6ec49eeecf16d70ee8cde57f7d881fe" 
$ PULL_PULL_SHA="28883326290e823552a955817d37af88ef31857d"
$ bases=$(git diff --name-status $PULL_BASE_SHA $PULL_PULL_SHA | grep -Po "^[^DR]\s+\K.*?(?=/)|^R\w*\s+.*\s+\K.*?(?=/)" | sort | uniq)
$ echo $bases
cluster-scope
```
As you can see, it returns the entire cluster-scope directory as the resulting diff, instead of the one file: `cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml`

**Comment by mimotej** [comment]
For now seems that upping resources fo kubeval is enough will have to investigate further why. It seems from short testing I have done it has a problem finding `PULL_BASE_SHA` but I will have to investigate further what might have caused it...

/assign

**Comment by mimotej** [comment]
Little update:
Problem seems to be in regex which is used after because what it does it matches highest layer in directory path meaning in this case `cluster-scope` 
![Screenshot from 2022-08-25 16-06-25](https://user-images.githubusercontent.com/47832967/186688334-44945b1e-0aca-44db-b42f-b15952b7d9b4.png)

If we figure out how to change this regex to match lowest possible layer in directory path it will fix it...

**Comment by tumido** [comment]
> As you can see, it returns the entire `cluster-scope` directory as the resulting diff, instead of the one file: `cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml`

Which is the correct outcome. Kubeval can't be run against partial manifests in base/overlays... Keep in mind that we modify and patch those manifests in overlays so for example subscription which requires a `channel` to be specified gains the value in overlay, etc.

The grep command is matching the root application folder intentionally because so far we don't have any heuristic to determine which base or overlay is including which modified file... And we need to run each change set through `kustomize build` before we can `kubeval` it, without it, partial manifests may not and won't fit the api spec resulting in false positives.

**Comment by Gregory-Pereira** [comment]
Then this seems to be logical and intended behaviour. I think this explanation coupled with your [PR to exclude some pre-submit checks based on the files changed](https://github.com/operate-first/apps/pull/2321) should resolve this issue. Would you agree @tumido, and if so can I close this?

**Comment by tumido** [comment]
I don't think this is an issue anymore.
