### ISSUE TITLE
Prow Fails to independently trigger all tests against PRs

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/apps#2318]
For PRs such as #2273 , or #2123 , Prow can identify test but not trigger them. I found reference to this in the logs that with the `/retest` the `hook` component does in fact know that the tests exists, but  simply cannot trigger them:
 
```
{"author":"Gregory-Pereira","component":"hook","event-GUID":"83187570-2718-11ed-8bd7-223c116faa98","event-type":"issue_comment","file":"prow/pjutil/filter.go:135","func":"k8s.io/test-infra/prow/pjutil.FilterPresubmits","level":"debug","msg":"Filtered 3 jobs, found 0 to trigger","org":"operate-first","plugin":"trigger","pr":2273,"repo":"apps","severity":"debug","time":"2022-08-28T21:30:18Z","to-trigger":null,"url":"https://github.com/operate-first/apps/pull/2273#issuecomment-1229557978"}
{"args":["gc.auto","0"],"client":"git","component":"hook","file":"prow/git/git.go:485","func":"k8s.io/test-infra/prow/git.(*Repo).Config","level":"info","msg":"Running git config.","severity":"info","time":"2022-08-28T21:31:27Z"}
```

However tests can be added by triggering them directly on the PR as is the case [here](https://github.com/operate-first/apps/pull/2273#issuecomment-1229565165). Not sure why this is happening, i'll be looking at the prow tests extensively this week.

/cc @harshad16  (to keep you informed of this)
/cc @HumairAK (if people have questions point them here)

**Comment by mimotej** [comment]
I think this is expected behaviour. [kustomize-build](https://github.com/operate-first/apps/blob/master/.prow.yaml#L5) and [kubeval-validation](https://github.com/operate-first/apps/blob/master/.prow.yaml#L24) have configured `run_if_changed` to files ending with `yaml`. First PR has only changes in `.md` and `.yml` files, second one has the same. I don't think there is a way how prow can find out that `yaml` and `yml` are extensions for the same type of file. Running these jobs manually will allow to run these jobs even though they are not run automatically. In this case we are also hitting #2294 because both these PRs change only documentation and therefore both `kustomize-build` and `kubeval-validation` will fail. We could change `run_if_changed: ".*yaml"` to `run_if_changed: ".*yaml|.*yml"` but right now I think this would cause many PRs to fail. 
/cc @tumido Is this correct? :point_up_2:

**Comment by VannTen** [comment]
Could we also be hitting this in https://github.com/thoth-station/slo-reporter/pull/361 ?

**Comment by Gregory-Pereira** [comment]
It seems that it is no longer an issue with regard to [the pr you referenced](https://github.com/thoth-station/slo-reporter/pull/361), however it may not appear that way because we are we're having a separate issue with OBCs on Smaug. This issue should generally be addressed by [Tom's PR](https://github.com/operate-first/apps/pull/2321), and will deduce that the exception you shared is a flake. Will re-open if more evidence comes to light.
/label priority/awaiting-more-evidence
/close
