### ISSUE TITLE
Add authentication via Openshift to Argo Workflows

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#39]
Ideally via openshift

**Comment by tumido** [comment]
We can do that just fine, once we have https://github.com/opendatahub-io/odh-manifests/pull/208 merged and applied. Argo Workflows [supports SSO since `v2.9`](https://argoproj.github.io/argo/argo-server-sso/#argo-server-sso) however, current ODH features `v2.7`.After my update we'll have the latest, `v2.12` available, hence we can do SSO. I'll take care of it.

**Comment by tumido** [comment]
POC with a standalone DEX https://github.com/tumido/odh-manifests/tree/argo-sso/argo 

```
kustomize build argo/components/dex | oc apply -f -
kustomize build argo/overlays/aiops-prod-argo | oc apply -f -
```
