### ISSUE TITLE
Auto Upgrade of OpenShift-pipeline v1.4.0 has breaking changes

### ISSUE THREAD

**Issue by harshad16** [operate-first/apps#579]
As the Openshift-pipeline is updated to v1.4.0 from v1.2.3, the requirements have introduced breaking changes.
The tekton-trigger in openshift-pipelinev1.2.3 was at v0.8.1 and it got updated v0.12.0 with openshift-pipeline v1.4.0 

**Updates to be done by users**:
Any **eventlistener** which was deployed needs to be updated with https://github.com/tektoncd/triggers/pull/898.

**Error message**:
`Error from server (BadRequest): admission webhook "validation.webhook.triggers.tekton.dev" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "name"`

**Fix requires admin privilege**:
As users would have to update the **eventlistener**, the tekton-trigger-webhook wouldn't let the eventlistener deployment get updated. 
For this to work, 
1. admin has to roll back tekton-trigger-webhook component to older version image.
`registry.redhat.io/openshift-pipelines-tech-preview/pipelines-triggers-webhook-rhel8@sha256:1125f608f4c2f5c7735152eb37a6167446d22e9445032dffe84c2782dd69f692`
2. delete the existing eventlistener. 
3. roll back up the tekton trigger webhook 
4.  update the new changes of the eventlistener deployment.

**Comment by 4n4nd** [comment]
cc @acidonper

**Comment by tumido** [comment]
Sorry for the inconvenience @harshad16. We learn from this experience.

What happen:
1. We had to switch the pipelines operator to `Automatic` install plan strategy because of  https://github.com/operate-first/apps/pull/559
2. We had many staled operator upgrades that (because of the OLM nature) required upgrading the same operator 2 or 3 times - we were upgrading 6 operators this way...
2. We didn't research if there's breaking changes in the updated operators, I've only checked the capabilities and was satisfied when I found out that Openshift Pipelines support "Seamless upgrade".
3. There seems to be no way to control Tekton component versions via Openshift Pipelines operator. It installs whatever version it pleases which makes it harder to control in the future.

> admin has to roll back tekton-trigger-webhook component to older version image.
registry.redhat.io/openshift-pipelines-tech-preview/pipelines-triggers-webhook-rhel8@sha256:1125f608f4c2f5c7735152eb37a6167446d22e9445032dffe84c2782dd69f692
delete the existing eventlistener.
roll back up the tekton trigger webhook
update the new changes of the eventlistener deployment.

@harshad16 is there any reason for this course of actions? Why can't we just delete the event listener?

**Comment by harshad16** [comment]
> is there any reason for this course of actions? Why can't we just delete the event listener?

The eventlistener CR is validated by the tekton-trigger-webhook, when the delete action is trigger on the event listener, the action is performed by this component tekton-trigger-webhook and the validation would fail (as the version of the webhook component is being updated).

**Comment by 4n4nd** [comment]
Along with @acidonper, following @harshad16 's instructions, I deleted all the instances of `EventListeners` that did not have the updated structure. Fortunately, all of these `EventListener` instances were owned by @acidonper. Now since the operator/crd has been updated along with all the instances of `EventListener` CRs, we should not see this issue again.

**Comment by tumido** [comment]
In future, it should be also possible to delete `EventListener`s by removing their finalizers and forcing a delete, making it no need to downgrade images.

**Comment by 4n4nd** [comment]
> In future, it should be also possible to delete `EventListener`s by removing their finalizers and forcing a delete, making it no need to downgrade images.

We tried doing that but we always got this error:
`Error from server (BadRequest): admission webhook "validation.webhook.triggers.tekton.dev" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "name"`

This issue should be reported upstream to `openshift-pipelines`. I think this was because the CR was not considered valid by the operator.

**Comment by tumido** [comment]
that is surprising, since without finalizer it should not even call the validation webhook.. interesting. :slightly_smiling_face:

**Comment by harshad16** [comment]
closing this issue.
If someone faces the same issue, we can point them here.
